source :rubygems
gem "haml", "2.2.24"
gem "rack", "1.2.1"
gem "rake", "0.8.7"
gem "sinatra", "1.0"
gem "sequel", "3.17.0"
gem "json", "1.4.6"
gem "activesupport", "2.3.2"
gem "pg", "0.9.0"
gem "sass", "3.1.0.alpha.23"
gem "activerecord"
gem "shotgun"
gem "bcrypt-ruby"
gem "rack-flash"
gem "sinatra-redirect-with-flash"
